// https://www.typescriptlang.org/docs/handbook/mixins.html

export type ClassType<T = object> = new (...args: any[]) => T;

// Questa serie di overloads permette di inferire il tipo dinamicamente in base ai mixin passati
//   WithEventTarget dipende da WithVideoElement, se componiamo una classe con l'ordine sbagliato
//   o una dipendenza mancante, verrà generato un errore in compile time

// TODO: trovare un modo migliore per il type inference

// biome-ignore format: <ack>
export function compose<T0 extends ClassType>(base: T0): T0;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType>(base: T0, m1: (base: T0) => T1): T1;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2,): T2;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3,): T3;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4,): T4;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5,): T5;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6,): T6;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7,): T7;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8,): T8;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9,): T9;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10,): T10;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11,): T11;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType, T12 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11, m12: (base: T11) => T12,): T12;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType, T12 extends ClassType, T13 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11, m12: (base: T11) => T12, m13: (base: T12) => T13,): T13;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType, T12 extends ClassType, T13 extends ClassType, T14 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11, m12: (base: T11) => T12, m13: (base: T12) => T13, m14: (base: T13) => T14,): T14;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType, T12 extends ClassType, T13 extends ClassType, T14 extends ClassType, T15 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11, m12: (base: T11) => T12, m13: (base: T12) => T13, m14: (base: T13) => T14, m15: (base: T14) => T15,): T15;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType, T12 extends ClassType, T13 extends ClassType, T14 extends ClassType, T15 extends ClassType, T16 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11, m12: (base: T11) => T12, m13: (base: T12) => T13, m14: (base: T13) => T14, m15: (base: T14) => T15, m16: (base: T15) => T16,): T16;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType, T12 extends ClassType, T13 extends ClassType, T14 extends ClassType, T15 extends ClassType, T16 extends ClassType, T17 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11, m12: (base: T11) => T12, m13: (base: T12) => T13, m14: (base: T13) => T14, m15: (base: T14) => T15, m16: (base: T15) => T16, m17: (base: T16) => T17,): T17;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType, T12 extends ClassType, T13 extends ClassType, T14 extends ClassType, T15 extends ClassType, T16 extends ClassType, T17 extends ClassType, T18 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11, m12: (base: T11) => T12, m13: (base: T12) => T13, m14: (base: T13) => T14, m15: (base: T14) => T15, m16: (base: T15) => T16, m17: (base: T16) => T17, m18: (base: T17) => T18,): T18;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType, T12 extends ClassType, T13 extends ClassType, T14 extends ClassType, T15 extends ClassType, T16 extends ClassType, T17 extends ClassType, T18 extends ClassType, T19 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11, m12: (base: T11) => T12, m13: (base: T12) => T13, m14: (base: T13) => T14, m15: (base: T14) => T15, m16: (base: T15) => T16, m17: (base: T16) => T17, m18: (base: T17) => T18, m19: (base: T18) => T19,): T19;
// biome-ignore format: <ack>
export function compose<T0 extends ClassType, T1 extends ClassType, T2 extends ClassType, T3 extends ClassType, T4 extends ClassType, T5 extends ClassType, T6 extends ClassType, T7 extends ClassType, T8 extends ClassType, T9 extends ClassType, T10 extends ClassType, T11 extends ClassType, T12 extends ClassType, T13 extends ClassType, T14 extends ClassType, T15 extends ClassType, T16 extends ClassType, T17 extends ClassType, T18 extends ClassType, T19 extends ClassType, T20 extends ClassType,>(base: T0, m1: (base: T0) => T1, m2: (base: T1) => T2, m3: (base: T2) => T3, m4: (base: T3) => T4, m5: (base: T4) => T5, m6: (base: T5) => T6, m7: (base: T6) => T7, m8: (base: T7) => T8, m9: (base: T8) => T9, m10: (base: T9) => T10, m11: (base: T10) => T11, m12: (base: T11) => T12, m13: (base: T12) => T13, m14: (base: T13) => T14, m15: (base: T14) => T15, m16: (base: T15) => T16, m17: (base: T16) => T17, m18: (base: T17) => T18, m19: (base: T18) => T19, m20: (base: T19) => T20,): T20;
// biome-ignore format: <ack>

export function compose(base: ClassType, ...mixins: Array<(base: ClassType) => ClassType>): ClassType {
  return mixins.reduce((cls, mixin) => mixin(cls), base);
}
